version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/fastapi-backend

permissions:
  - object: /var/www/fastapi-backend
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: scripts/start_fastapi.sh
      timeout: 300
      runas: ec2-user
